-- Sówki PWA v0.7.3 — anonimowy licznik „Daj Sówkę”
-- Uruchom całość w Supabase → SQL Editor → Run.
--
-- Co zapisujemy:
--   * rodzaj treści: notice / event / announcement,
--   * ID wpisu,
--   * anonimowy skrót losowego identyfikatora urządzenia,
--   * czas pierwszego kliknięcia.
-- Nie zapisujemy imienia rodzica, dziecka, e-maila, telefonu ani adresu IP w tej tabeli.

begin;

create table if not exists public.sowka_reads (
  id bigint generated by default as identity primary key,
  content_kind text not null,
  item_id bigint not null,
  device_hash text not null,
  created_at timestamptz not null default now(),
  constraint sowka_reads_kind_check
    check (content_kind in ('notice','event','announcement')),
  constraint sowka_reads_device_hash_len
    check (char_length(device_hash)=32)
);

create unique index if not exists sowka_reads_unique_device_item
on public.sowka_reads(content_kind,item_id,device_hash);

create index if not exists sowka_reads_content_idx
on public.sowka_reads(content_kind,item_id);

alter table public.sowka_reads enable row level security;

-- Rodzice nie mają bezpośredniego dostępu do tabeli.
revoke all on public.sowka_reads from anon, authenticated;

-- Rodzic wywołuje tylko tę kontrolowaną funkcję RPC.
create or replace function public.give_sowka(
  p_kind text,
  p_item_id bigint,
  p_device_token uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_exists boolean := false;
  v_hash text;
begin
  if p_kind not in ('notice','event','announcement')
     or p_item_id is null
     or p_item_id <= 0
     or p_device_token is null then
    return false;
  end if;

  if p_kind='notice' then
    select exists(
      select 1 from public.monthly_notices
      where id=p_item_id and published=true
    ) into v_exists;
  elsif p_kind='event' then
    select exists(
      select 1 from public.events
      where id=p_item_id and published=true
    ) into v_exists;
  elsif p_kind='announcement' then
    select exists(
      select 1 from public.announcements
      where id=p_item_id and published=true
    ) into v_exists;
  end if;

  if not v_exists then
    return false;
  end if;

  -- Do tabeli nie trafia nawet sam losowy UUID urządzenia.
  v_hash := md5(p_device_token::text || ':sowki-read-v1');

  insert into public.sowka_reads(content_kind,item_id,device_hash)
  values(p_kind,p_item_id,v_hash)
  on conflict(content_kind,item_id,device_hash) do nothing;

  -- TRUE oznacza: wpis był prawidłowy. Powtórne kliknięcie tego samego
  -- urządzenia nie zwiększa licznika dzięki UNIQUE.
  return true;
end;
$$;

revoke all on function public.give_sowka(text,bigint,uuid) from public;
grant execute on function public.give_sowka(text,bigint,uuid) to anon, authenticated;

-- Liczniki widzi wyłącznie zalogowany administrator.
create or replace function public.get_sowka_counts(p_kind text)
returns table(item_id bigint, sowka_count bigint)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.is_sowki_admin() then
    raise exception 'Forbidden' using errcode='42501';
  end if;

  if p_kind not in ('notice','event','announcement') then
    raise exception 'Invalid content kind' using errcode='22023';
  end if;

  return query
  select r.item_id, count(*)::bigint
  from public.sowka_reads r
  where r.content_kind=p_kind
  group by r.item_id
  order by r.item_id;
end;
$$;

revoke all on function public.get_sowka_counts(text) from public;
grant execute on function public.get_sowka_counts(text) to authenticated;

-- Sprzątanie anonimowych reakcji po trwałym usunięciu wpisu.
create or replace function private.cleanup_sowka_reads()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_kind text;
begin
  v_kind := case TG_TABLE_NAME
    when 'monthly_notices' then 'notice'
    when 'events' then 'event'
    when 'announcements' then 'announcement'
    else null
  end;

  if v_kind is not null then
    delete from public.sowka_reads
    where content_kind=v_kind and item_id=old.id;
  end if;

  return old;
end;
$$;

drop trigger if exists sowka_cleanup_monthly_notices on public.monthly_notices;
create trigger sowka_cleanup_monthly_notices
after delete on public.monthly_notices
for each row execute function private.cleanup_sowka_reads();

drop trigger if exists sowka_cleanup_events on public.events;
create trigger sowka_cleanup_events
after delete on public.events
for each row execute function private.cleanup_sowka_reads();

drop trigger if exists sowka_cleanup_announcements on public.announcements;
create trigger sowka_cleanup_announcements
after delete on public.announcements
for each row execute function private.cleanup_sowka_reads();

commit;

-- Kontrola po wdrożeniu (opcjonalnie, jako admin w SQL Editor):
-- select content_kind,item_id,count(*) as sowki
-- from public.sowka_reads
-- group by content_kind,item_id
-- order by content_kind,item_id;
