-- ============================================================
-- Sówki PWA v0.5.5.2 — anonimowe statystyki odwiedzin działów
-- ============================================================
-- Zapisywane są WYŁĄCZNIE:
--   - nazwa działu
--   - data i godzina wejścia
-- Nie zapisujemy maila, imienia, IP, identyfikatora urządzenia ani rodzica.
--
-- Statystyki mogą odczytać tylko osoby będące w public.admin_users.

begin;

create table if not exists public.app_page_views (
  id bigint generated by default as identity primary key,
  page text not null,
  viewed_at timestamptz not null default now(),
  constraint app_page_views_page_check check (
    page in (
      'home',
      'notificationsPage',
      'announcementsPage',
      'menu',
      'calendar',
      'surveysPage',
      'gallery',
      'payments'
    )
  )
);

create index if not exists app_page_views_viewed_at_idx
  on public.app_page_views (viewed_at desc);

create index if not exists app_page_views_page_viewed_at_idx
  on public.app_page_views (page, viewed_at desc);

alter table public.app_page_views enable row level security;

-- Nie udostępniamy tabeli bezpośrednio frontendowi.
revoke all on table public.app_page_views from anon, authenticated;
revoke all on sequence public.app_page_views_id_seq from anon, authenticated;

-- ------------------------------------------------------------
-- Publiczny, anonimowy zapis pojedynczego wejścia.
-- Funkcja przyjmuje tylko z góry określone nazwy działów.
-- ------------------------------------------------------------
create or replace function public.track_page_view(p_page text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_page not in (
    'home',
    'notificationsPage',
    'announcementsPage',
    'menu',
    'calendar',
    'surveysPage',
    'gallery',
    'payments'
  ) then
    return;
  end if;

  insert into public.app_page_views(page)
  values (p_page);
end;
$$;

revoke all on function public.track_page_view(text) from public;
grant execute on function public.track_page_view(text) to anon, authenticated;

-- ------------------------------------------------------------
-- Suma wejść według działu.
-- p_days:
--   7,30,90 = ostatnie N dni
--   0       = cały okres
-- ------------------------------------------------------------
create or replace function public.get_page_view_stats(p_days integer default 30)
returns table(page text, views bigint)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.is_sowki_admin() then
    raise exception 'Forbidden' using errcode = '42501';
  end if;

  return query
  select
    v.page,
    count(*)::bigint as views
  from public.app_page_views v
  where
    coalesce(p_days,30) <= 0
    or v.viewed_at >= now() - make_interval(days => coalesce(p_days,30))
  group by v.page
  order by views desc, v.page;
end;
$$;

revoke all on function public.get_page_view_stats(integer) from public;
grant execute on function public.get_page_view_stats(integer) to authenticated;

-- ------------------------------------------------------------
-- Podział wejść na każdy dzień wg strefy Europe/Warsaw.
-- ------------------------------------------------------------
create or replace function public.get_page_view_daily(p_days integer default 30)
returns table(day date, page text, views bigint)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.is_sowki_admin() then
    raise exception 'Forbidden' using errcode = '42501';
  end if;

  return query
  select
    (timezone('Europe/Warsaw',v.viewed_at))::date as day,
    v.page,
    count(*)::bigint as views
  from public.app_page_views v
  where
    coalesce(p_days,30) <= 0
    or v.viewed_at >= now() - make_interval(days => coalesce(p_days,30))
  group by
    (timezone('Europe/Warsaw',v.viewed_at))::date,
    v.page
  order by day desc, views desc, v.page;
end;
$$;

revoke all on function public.get_page_view_daily(integer) from public;
grant execute on function public.get_page_view_daily(integer) to authenticated;

commit;
