-- Sówki PWA v0.6.9 — automatyczne przekazywanie wiadomości e-mail
-- Wymaga wdrożenia Edge Function: send-parent-message-email
-- Funkcję należy wdrożyć z wyłączoną opcją Verify JWT.

begin;

create table if not exists public.message_recipients (
  id bigint generated by default as identity primary key,
  display_name text not null,
  role text,
  email text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint message_recipients_name_len check (char_length(display_name) between 1 and 120),
  constraint message_recipients_role_len check (role is null or char_length(role) <= 120),
  constraint message_recipients_email_len check (char_length(email) between 3 and 254)
);

create unique index if not exists message_recipients_email_unique
on public.message_recipients (lower(email));

alter table public.message_recipients enable row level security;

revoke all on public.message_recipients from anon;
revoke all on public.message_recipients from authenticated;

grant select, insert, update, delete
on public.message_recipients
to authenticated;

drop policy if exists "sowki_admin_read_message_recipients" on public.message_recipients;
create policy "sowki_admin_read_message_recipients"
on public.message_recipients
for select
to authenticated
using (private.is_sowki_admin());

drop policy if exists "sowki_admin_insert_message_recipients" on public.message_recipients;
create policy "sowki_admin_insert_message_recipients"
on public.message_recipients
for insert
to authenticated
with check (private.is_sowki_admin());

drop policy if exists "sowki_admin_update_message_recipients" on public.message_recipients;
create policy "sowki_admin_update_message_recipients"
on public.message_recipients
for update
to authenticated
using (private.is_sowki_admin())
with check (private.is_sowki_admin());

drop policy if exists "sowki_admin_delete_message_recipients" on public.message_recipients;
create policy "sowki_admin_delete_message_recipients"
on public.message_recipients
for delete
to authenticated
using (private.is_sowki_admin());

alter table public.parent_messages
  add column if not exists email_status text not null default 'pending';

alter table public.parent_messages
  add column if not exists email_sent_at timestamptz;

alter table public.parent_messages
  add column if not exists email_error text;

alter table public.parent_messages
  add column if not exists email_recipient_count integer not null default 0;

alter table public.parent_messages
  add column if not exists email_success_count integer not null default 0;

-- Starszych wiadomości nie próbujemy wysyłać ponownie.
update public.parent_messages
set email_status='legacy'
where email_status='pending'
  and email_sent_at is null;

commit;

create extension if not exists pg_net;

create or replace function private.forward_parent_message_email()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform net.http_post(
    url := 'https://wztxwoernzjjarprrzjl.supabase.co/functions/v1/send-parent-message-email',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'x-sowki-mail-secret','HpEg3uGavBbD4UQMRoqMTDvz87-S0IheDMVwu5rYmPCiDYLu'
    ),
    body := jsonb_build_object('message_id', new.id)
  );

  return new;
end;
$$;

drop trigger if exists sowki_forward_parent_message_email
on public.parent_messages;

create trigger sowki_forward_parent_message_email
after insert on public.parent_messages
for each row
execute function private.forward_parent_message_email();

-- Od teraz każdy NOWY rekord ma status pending przed wysyłką.
alter table public.parent_messages
  alter column email_status set default 'pending';

-- Kontrola odbiorców po konfiguracji:
-- select id, display_name, role, email, active
-- from public.message_recipients
-- order by active desc, display_name;

