-- ============================================================
-- Sówki PWA v0.5.5.7 — prosta skrzynka wiadomości od rodziców
-- ============================================================
-- Rodzic nie musi mieć konta.
-- Wiadomości mogą odczytać / oznaczać / usuwać wyłącznie administratorzy.
-- Rodzic nie ma dostępu do listy wiadomości ani odpowiedzi w aplikacji.

begin;

create table if not exists public.parent_messages (
  id bigint generated by default as identity primary key,
  parent_name text not null,
  child_name text not null,
  contact text not null,
  message text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists parent_messages_created_at_idx
  on public.parent_messages (created_at desc);

create index if not exists parent_messages_unread_idx
  on public.parent_messages (read_at, created_at desc);

alter table public.parent_messages enable row level security;

-- Tabela nie jest dostępna bezpośrednio publicznie.
revoke all on table public.parent_messages from anon, authenticated;
revoke all on sequence public.parent_messages_id_seq from anon, authenticated;

-- Administratorzy mogą przeglądać wiadomości.
drop policy if exists "parent_messages_admin_select" on public.parent_messages;
create policy "parent_messages_admin_select"
on public.parent_messages
for select
to authenticated
using (private.is_sowki_admin());

-- Administratorzy mogą oznaczać jako przeczytane / nieprzeczytane.
drop policy if exists "parent_messages_admin_update" on public.parent_messages;
create policy "parent_messages_admin_update"
on public.parent_messages
for update
to authenticated
using (private.is_sowki_admin())
with check (private.is_sowki_admin());

-- Administratorzy mogą usuwać wiadomości.
drop policy if exists "parent_messages_admin_delete" on public.parent_messages;
create policy "parent_messages_admin_delete"
on public.parent_messages
for delete
to authenticated
using (private.is_sowki_admin());

grant select, update, delete
on table public.parent_messages
to authenticated;

-- ------------------------------------------------------------
-- Publiczna funkcja do wysłania wiadomości.
-- Rodzic nie otrzymuje żadnego dostępu do samej tabeli.
-- ------------------------------------------------------------
create or replace function public.submit_parent_message(
  p_parent_name text,
  p_child_name text,
  p_contact text,
  p_message text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_id bigint;
begin
  p_parent_name := btrim(coalesce(p_parent_name,''));
  p_child_name := btrim(coalesce(p_child_name,''));
  p_contact := btrim(coalesce(p_contact,''));
  p_message := btrim(coalesce(p_message,''));

  if char_length(p_parent_name) < 2 or char_length(p_parent_name) > 100 then
    raise exception 'Nieprawidłowe imię i nazwisko rodzica.';
  end if;

  if char_length(p_child_name) < 2 or char_length(p_child_name) > 80 then
    raise exception 'Nieprawidłowe imię dziecka.';
  end if;

  if char_length(p_contact) < 3 or char_length(p_contact) > 150 then
    raise exception 'Nieprawidłowy kontakt zwrotny.';
  end if;

  if char_length(p_message) < 2 or char_length(p_message) > 1500 then
    raise exception 'Wiadomość ma nieprawidłową długość.';
  end if;

  insert into public.parent_messages(
    parent_name,
    child_name,
    contact,
    message
  )
  values (
    p_parent_name,
    p_child_name,
    p_contact,
    p_message
  )
  returning id into new_id;

  return new_id;
end;
$$;

revoke all on function public.submit_parent_message(text,text,text,text) from public;
grant execute on function public.submit_parent_message(text,text,text,text) to anon, authenticated;

commit;
